application: fried-python
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: PIL
  version: latest

builtins:
- appstats: on

inbound_services:
- warmup