application: fried-python
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: static

- url: /admin
  script: admin.py
  login: admin

- url: /admin/.*
  script: admin.py
  login: admin

- url: /blog
  script: blog.app

- url: .*
  script: main.app

builtins:
- appstats: on

inbound_services:
- warmup
