application: fried-python
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_dir: static/favicon.ico
  upload: static/favicon.ico

- url: .*
  script: main.app

builtins:
- appstats: on

inbound_services:
- warmup
